
import { createClient } from '@supabase/supabase-js';

export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
//sending the access token to the supabase client to see if user is authenticated to access or not
const supabaseClient = async(supabaseAccessToken)=>{
    //here supabaseaccesstoken is the clerk token generated by clerk for that user
    //and below createclient will set up a connection to your Supabase database using the URL and anon key.
const supabase = createClient(supabaseUrl, supabaseKey, {
    //clerk ke liye supabaseaccesstoken headers mai diya jata hai
    global: {
        headers: {
        Authorization: `Bearer ${supabaseAccessToken}`,
        //The global object adds custom settings that apply to all requests made by this client.
        // Inside global, there's a headers object that includes an Authorization header: Bearer ${supabaseAccessToken}.
        // This header sends the Clerk token with every API call to Supabase.
        // "Bearer" is just the standard way to send tokens in HTTP headers.
        // This lets Supabase know which user is making the request (for Row Level Security).
        },  
    },
});

return supabase;
}

export default supabaseClient
        


// What is this and why is it used?
// Purpose:
// This file exports a function that creates a Supabase client configured for the currently authenticated Clerk user.
// Why:
// When using Clerk for authentication and Supabase for your database, you need to send the user's access token to Supabase. This allows Supabase to enforce Row Level Security (RLS) and know which user is making requests.
// How to use:
// Call supabaseClient(clerkAccessToken) to get a Supabase client that sends the correct Authorization header for the current use 

//What Happens in the supabaseClient Function
// This is an async function that creates and returns a customized Supabase client. Here's the flow:

// Input: supabaseAccessToken (a parameter you pass in):
// This is not a Supabase token—it's an access token from Clerk (your authentication provider).
// Clerk generates this token after a user logs in. It proves the user is authenticated and includes details like their user ID.

// Creating the Supabase Client:
// createClient(supabaseUrl, supabaseKey, { ... }) sets up a connection to your Supabase database using the URL and anon key.
// The global object adds custom settings that apply to all requests made by this client.
// Inside global, there's a headers object that includes an Authorization header: Bearer ${supabaseAccessToken}.
// This header sends the Clerk token with every API call to Supabase.
// "Bearer" is just the standard way to send tokens in HTTP headers.

// Why the Authorization Header?
// Supabase uses this to know which user is making the request.
// It enables Row Level Security (RLS)—a Supabase feature that restricts database access based on the user.
// Without this, Supabase treats requests as anonymous (using the anon key), and you can't enforce user-specific rules (e.g., "only show jobs posted by this user").

//IMPORTANT
// Return Value:
// The function returns the configured supabase client object.
// You can now use this client to query your database (e.g., supabase.from('jobs').select('*')), and Supabase will automatically apply the user's permissions.
// How Clerk is Linked (Integration with Your Project)
// Clerk is your authentication system (handles sign-up, login, user sessions). Supabase is your database. They work together like this:


// User Logs In via Clerk:
// When a user signs in (e.g., via your app's login page), Clerk creates a session and generates an accessToken (the supabaseAccessToken in the function).
// This token is short-lived and tied to the user's identity.

// Passing the Token to Supabase:
// In your app, you call supabaseClient(clerkAccessToken) to get a client.

// Secure Database Access:
// With the token, Supabase enforces rules like ===
//Users can only see/edit their own jobs.
// Admins can see everything.
// Without Clerk's token, requests are anonymous and limited.

// Why This Setup?
// Separation of Concerns: Clerk handles auth (who the user is), Supabase handles data (what they can access).
// Security: No storing passwords in Supabase; Clerk manages that.
// Scalability: Easy to add features like social logins or multi-factor auth via Clerk.

// Common Usage in Your App
// You'd call this function in components that need database access (e.g., in apiJobs.js or pages like job-listing.jsx).
// Always get the token fresh from Clerk before creating the client—tokens expire.
// If the token is invalid, Supabase will reject requests, and you can handle errors (e.g., redirect to login).


